properties
storePassword=YaronhsHnk682dx!6089
keyPassword=YaronhsHnk682dx!6089
keyAlias=upload
storeFile=Cproperties
storePassword=your_password
keyPassword=your_password
keyAlias=upload
storeFile=C:\\Users\\Shira\\Downloads\\New folder\\OpenCode\\upload-keystore.jks:\\Users\\Shira\\Downloads\\New folder\\OpenCode\\upload-keystore.jks